version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: test_system
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - web

volumes:
  postgres_data: {}
